include: package:lint/analysis_options.yaml
analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    avoid_positional_boolean_parameters: ignore
    avoid_function_literals_in_foreach_calls: ignore
    prefer_for_elements_to_map_fromiterable: ignore
    prefer_if_elements_to_conditional_expressions: ignore
    constant_identifier_names: ignore
