name: data_setup
description: AbsApp Setup

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  path_provider: ^1.6.5
  mobx: ^1.0.2+2
  flutter_mobx: ^1.0.1
  provider: ^3.2.0
  dartz: ^0.8.9
  freezed_annotation: ^0.7.1
  json_annotation: ^3.0.1
  meta: ^1.1.8
  http:
  intl:

dev_dependencies:
  lint: ^1.1.1
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.0+2
  mobx_codegen: ^1.0.2
  build_runner:
  freezed: ^0.9.2
  json_serializable: ^3.2.5

flutter:
  uses-material-design: true
