name: data_setup
description: AbsApp Setup

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  path_provider: ^1.6.5
  mobx: ^1.0.2+2
  flutter_mobx: ^1.0.1
  provider: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.0+2
  mobx_codegen: ^1.0.2
  build_runner:

flutter:
  uses-material-design: true
