name: abs_up
description: Abs Up from the Misfit Coach

version: 1.0.0+1

# to update application ip change here and run:
# flutter pub run flutter_application_id:main -f pubspec.yaml
flutter_application_id:
  android:
    id: "com.misfitcoders.absup"
    #name: Abs Up"
  ios:
    id: "com.misfitcoders.absup"
    #name: "Abs Up"

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  flutter_tts: ^1.0.0

  # Firebase Dependencies
  cloud_firestore: ^0.13.5
  firebase_core: ^0.4.4+3
  firebase_analytics: ^5.0.11
  firebase_auth: ^0.16.0
  google_sign_in: ^4.4.4

  uuid: ^2.0.4
  fluro: ^1.6.3
  hive: 1.4.1+1
  hive_flutter: 0.3.0+2
  path_provider:
  mobx: ^1.1.1
  flutter_mobx: ^1.1.0
  provider: ^4.0.5
  dartz: ^0.9.1
  freezed_annotation: ^0.7.1
  json_annotation: ^3.0.1
  meta: ^1.1.8
  http: ^0.12.1
  intl:
  get_it: ^4.0.2
  injectable: ^0.3.0
  flutter_markdown: ^0.3.5

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  lint: ^1.2.0
  hive_generator: ^0.7.0+2
  mobx_codegen: ^1.0.3
  build_runner: ^1.9.0
  freezed: ^0.10.8
  json_serializable: ^3.2.5
  injectable_generator: ^0.3.5
  flutter_application_id: "^1.0.0"

flutter:
  uses-material-design: true

  assets:
    - assets/data/exercises.json
    - assets/exercise_images/
    - assets/exercise_details/

  fonts:
    - family: AbsAppIcons
      fonts:
        - asset: assets/fonts/AbsAppIcons.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          style: italic
          weight: 500
