name: data_setup
description: AbsApp Setup

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:

  # Firebase Dependencies
  cloud_firestore:
  firebase_core:
  firebase_auth:
  google_sign_in:

  fluro:
  hive: 1.4.1+1
  hive_flutter: 0.3.0+2
  path_provider:
  mobx:
  flutter_mobx:
  provider: ^3.2.0
  dartz:
  freezed_annotation: ^0.7.1
  json_annotation: ^3.0.1
  meta: ^1.1.8
  http:
  intl:
  flutter_markdown: ^0.3.4

dev_dependencies:
  lint:
  #flutter_test:
  #  sdk: flutter
  hive_generator: ^0.7.0+2
  mobx_codegen:
  build_runner:
  freezed: ^0.9.2
  json_serializable: ^3.2.5

flutter:
  uses-material-design: true

  assets:
    - assets/data/exercises.json
    - assets/exercise_images/
    - assets/exercise_details/

  fonts:
    - family: AbsAppIcons
      fonts:
        - asset: assets/fonts/AbsAppIcons.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          style: italic
          weight: 500
