name: abs_up
description: Abs Up from the Misfit Coach

version: 0.0.1+1

# to update application ip change here and run:
# flutter pub run flutter_application_id:main -f pubspec.yaml
flutter_application_id:
  android:
    id: "com.misfitcoders.abs_up"
    #name: "Abs Up"
  ios:
    id: "com.misfitcoders.abs_up"
    #name: "Abs Up"

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/icon.png"

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  flutter_tts: ^1.2.2
  font_awesome_flutter: ^8.8.1
  video_player: ^0.10.11+1
  native_video_view: ^0.2.1
  flutter_launcher_icons: ^0.7.5
  sign_in_with_apple: ^2.4.0
  webview_flutter: ^0.3.22+1
  wiredash: ^0.2.0
  simple_moment: ^1.0.5+1

  # Google Dependencies
  cloud_firestore: ^0.13.6
  firebase_core: ^0.4.5
  firebase_analytics: ^5.0.15
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1

  uuid: ^2.0.4
  flushbar: ^1.10.4
  fluro: ^1.6.3
  # hive: 1.4.1+1
  # hive_flutter: 0.3.0+2
  path_provider:
  mobx: ^1.2.1
  flutter_mobx: ^1.1.0
  provider: ^4.1.3
  dartz: ^0.9.1
  freezed_annotation: ^0.7.1
  json_annotation: ^3.0.1
  meta: ^1.1.8
  http: ^0.12.1
  intl:
  get_it: ^4.0.2
  injectable: ^0.3.0
  flutter_markdown: ^0.3.5
  path: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.2.0
  # hive_generator: ^0.7.0+2
  mobx_codegen: ^1.1.0
  build_runner: ^1.10.0
  freezed: ^0.10.8
  json_serializable: ^3.2.5
  injectable_generator: ^0.3.5
  flutter_application_id: "^1.0.0"

# override to comply with hive_flutter not compatible with flutter_test sdk
dependency_overrides:
  path: ^1.6.4
  dartx: ^0.3.0
  characters: ^0.3.0
  hive:
    git:
      url: https://github.com/hivedb/hive
      path: hive
      # uncomment below to get a working commit
      #ref: d7ee72537a3b7ce1284bcbf5ee5f86e617a4f6fc
  hive_generator:
    git:
      url: https://github.com/hivedb/hive
      path: hive_generator
      # uncomment below to get a working commit
      #ref: d7ee72537a3b7ce1284bcbf5ee5f86e617a4f6fc
  hive_flutter:
    git:
      url: https://github.com/hivedb/hive
      path: hive_flutter
      # uncomment below to get a working commit
      #ref: d7ee72537a3b7ce1284bcbf5ee5f86e617a4f6fc

flutter:
  uses-material-design: true

  assets:
    - assets/app_images/
    - assets/data/exercises.json
    - assets/exercise_images/
    - assets/exercise_media/

  fonts:
    - family: AbsAppIcons
      fonts:
        - asset: assets/fonts/AbsAppIcons.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          style: italic
          weight: 500
