name: abs_up_admin
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^0.6.7
  cloud_firestore: ^0.14.0+2
  copy_with_extension: ">=1.0.0 <2.0.0"
  cupertino_icons: ^0.1.3
  dartz: ^0.9.2
  equatable: ^1.2.5
  expandable_widget: ^1.0.5
  extended_sliver: ^1.0.1
  firebase_analytics: ^6.0.0
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  firebase_dynamic_links: ^0.6.0
  firebase_messaging: ^7.0.0
  flutter_local_notifications: ^1.4.4+4
  flutter_local_notifications_platform_interface: ^1.0.1
  flutter_neumorphic: ^3.0.1
  freezed_annotation: ^0.12.0
  get_it: ^4.0.4
  google_sign_in: ^4.5.3
  googleapis: ^0.55.0
  googleapis_auth: ^0.2.12
  http: ^0.12.2
  injectable: ^1.0.4
  meta: ^1.2.3
  motion_tab_bar: ^0.1.5
  neumorphic: ^0.4.0
  observable_ish: ^2.1.4
  path: ^1.7.0
  path_provider: ^1.6.14
  popup_menu: ^1.0.5
  pull_to_refresh_notification: ^1.1.2
  stacked: ^1.7.6
  stacked_services: ^0.5.4+2
  table_calendar: ^2.2.3
  uuid: ^2.2.2
  wiredash: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.8
  build_runner: ^1.10.2
  cloud_firestore_mocks: ^0.5.0+1
  copy_with_extension_gen: ">=1.0.0 <2.0.0"
  firebase_auth_mocks: ^0.3.1
  freezed: ^0.12.1
  google_sign_in_mocks: ^0.1.0+2

  # code generators
  hive_generator: ^0.7.1
  injectable_generator: ^1.0.4
  json_serializable: ^3.4.1
  lint: ^1.2.0
  mockito: ^4.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/
    - assets/fonts/
